# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitrespect < Formula
  desc "Respect your git work with real metrics. Measure AI productivity impact."
  homepage "https://github.com/juangracia/gitrespect"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juangracia/gitrespect/releases/download/v0.2.1/gitrespect-darwin-amd64.tar.gz"
      sha256 "8d330d5a8df93923626b137aa94a7c491b9d5aaedb9450c6326a1dd44a12be4c"

      def install
        bin.install "gitrespect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juangracia/gitrespect/releases/download/v0.2.1/gitrespect-darwin-arm64.tar.gz"
      sha256 "639cd7c2e595eb2c6652ad99140349db5384c9eaee933a1c924cf6adeb986abb"

      def install
        bin.install "gitrespect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juangracia/gitrespect/releases/download/v0.2.1/gitrespect-linux-amd64.tar.gz"
      sha256 "29e2a1a2708bc20fb0dfca08e2d4d3eb653d9f321101d23faa04d9ccdf5353c0"
      def install
        bin.install "gitrespect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juangracia/gitrespect/releases/download/v0.2.1/gitrespect-linux-arm64.tar.gz"
      sha256 "9effc49af147aca8d746221a19ccf5c46b3eb082ee721dced7a441f0f420ba8a"
      def install
        bin.install "gitrespect"
      end
    end
  end

  test do
    system "#{bin}/gitrespect", "version"
  end
end
